"""FIX 4.4 tag definitions for AllocationInstruction (MsgType J)."""

# Header tags
BEGIN_STRING = 8
BODY_LENGTH = 9
MSG_TYPE = 35
SENDER_COMP_ID = 49
TARGET_COMP_ID = 56
MSG_SEQ_NUM = 34
SENDING_TIME = 52

# Trade-level tags
ALLOC_ID = 70
ALLOC_TRANS_TYPE = 71
REF_ALLOC_ID = 72
SIDE = 54
SYMBOL = 55
QUANTITY = 53

# Orders group
NO_ORDERS = 73
ORDER_ID = 37

# Allocations group
NO_ALLOCS = 78
ALLOC_ACCOUNT = 79
ALLOC_QTY = 80
ALLOC_PRICE = 366
INDIVIDUAL_ALLOC_ID = 467

# Parties group
NO_PARTY_IDS = 453
PARTY_ID = 448
PARTY_ID_SOURCE = 447
PARTY_ROLE = 452

# Trailer
CHECKSUM = 10

# PartyRole codes
PARTY_ROLE_EXECUTING_FIRM = 1
PARTY_ROLE_CLIENT_ID = 3
PARTY_ROLE_CLEARING_FIRM = 4
PARTY_ROLE_INVESTOR_ID = 5
PARTY_ROLE_INTRODUCING_FIRM = 6
PARTY_ROLE_ORDER_ORIGIN_FIRM = 13
PARTY_ROLE_GIVEUP_CLEARING_FIRM = 14